export const COUNTRY_NAME_TO_ID: Record<string, string> = {
  afghanistan: "AF",
  albania: "AL",
  algeria: "DZ",
  angola: "AO",
  argentina: "AR",
  australia: "AU",
  austria: "AT",
  azerbaijan: "AZ",
  bangladesh: "BD",
  belgium: "BE",
  benin: "BJ",
  bolivia: "BO",
  botswana: "BW",
  brazil: "BR",
  bulgaria: "BG",
  burkina: "BF",
  burundi: "BI",
  cambodia: "KH",
  cameroon: "CM",
  canada: "CA",
  chad: "TD",
  chile: "CL",
  china: "CN",
  colombia: "CO",
  congo: "CG",
  "costa rica": "CR",
  croatia: "HR",
  cuba: "CU",
  "czech republic": "CZ",
  denmark: "DK",
  "dominican republic": "DO",
  ecuador: "EC",
  egypt: "EG",
  ethiopia: "ET",
  finland: "FI",
  france: "FR",
  gabon: "GA",
  gambia: "GM",
  germany: "DE",
  ghana: "GH",
  greece: "GR",
  guatemala: "GT",
  guinea: "GN",
  haiti: "HT",
  honduras: "HN",
  hungary: "HU",
  india: "IN",
  indonesia: "ID",
  iran: "IR",
  iraq: "IQ",
  ireland: "IE",
  israel: "IL",
  italy: "IT",
  "ivory coast": "CI",
  jamaica: "JM",
  japan: "JP",
  jordan: "JO",
  kazakhstan: "KZ",
  kenya: "KE",
  kuwait: "KW",
  lebanon: "LB",
  liberia: "LR",
  libya: "LY",
  madagascar: "MG",
  malawi: "MW",
  malaysia: "MY",
  mali: "ML",
  mauritania: "MR",
  mauritius: "MU",
  mexico: "MX",
  moldova: "MD",
  morocco: "MA",
  mozambique: "MZ",
  myanmar: "MM",
  namibia: "NA",
  nepal: "NP",
  netherlands: "NL",
  "new zealand": "NZ",
  nicaragua: "NI",
  niger: "NE",
  nigeria: "NG",
  norway: "NO",
  pakistan: "PK",
  panama: "PA",
  paraguay: "PY",
  peru: "PE",
  philippines: "PH",
  poland: "PL",
  portugal: "PT",
  romania: "RO",
  russia: "RU",
  rwanda: "RW",
  "saudi arabia": "SA",
  senegal: "SN",
  "sierra leone": "SL",
  somalia: "SO",
  "south africa": "ZA",
  "south sudan": "SS",
  spain: "ES",
  "sri lanka": "LK",
  sudan: "SD",
  sweden: "SE",
  switzerland: "CH",
  syria: "SY",
  tanzania: "TZ",
  thailand: "TH",
  togo: "TG",
  tunisia: "TN",
  turkey: "TR",
  uganda: "UG",
  ukraine: "UA",
  "united kingdom": "GB",
  "united states": "US",
  usa: "US",
  uk: "GB",
  uruguay: "UY",
  uzbekistan: "UZ",
  venezuela: "VE",
  vietnam: "VN",
  yemen: "YE",
  zambia: "ZM",
  zimbabwe: "ZW",
};

export function resolveCountryId(input: string): string | null {
  const normalized = input.toLowerCase().trim();
  return COUNTRY_NAME_TO_ID[normalized] ?? null;
}
